### ISSUE TITLE
Spaces issue

### ISSUE THREAD

**Issue by imadsani** [AfaanBilal/gitlab-autodeploy-v2#1]
The deploy script will not deploy file names with spaces. 

The php error log throws the following errors:

 PHP Warning:  file_get_contents(https://gitlab.com/api/v3/projects/2244378/repository/files?private_token=&amp;ref=development&amp;file_path=afger  awergwqergwerg.txt): failed to open stream: HTTP request failed! HTTP/1.0 400 Bad Request in httpdocs/git2.php on line 155
 PHP Warning:  array_keys() expects parameter 1 to be array, null given in /httpdocs/git2.php on line 158
 PHP Warning:  in_array() expects parameter 2 to be array, null given in /httpdocs/git2.php on line 158
 PHP Warning:  mkdir(): Invalid path in /httpdocs/git2.php on line 176
 PHP Warning:  file_put_contents(): Filename cannot be empty in /httpdocs/git2.php on line 178

**Comment by AfaanBilal** [comment]
Thank you for pointing this out. I have fixed the issue.
